### ISSUE TITLE
Matchbox Ingress resource example doesn't work w Nginx Ingress Controller 0.9-beta.7

### ISSUE THREAD

**Issue by dghubble** [coreos/matchbox#575]
Upgrading [nginx-ingress-controller](https://github.com/kubernetes/ingress) from 0.9-beta.3 to 0.9-beta.7, the Matchbox [Ingress](https://github.com/coreos/matchbox/blob/master/contrib/k8s/matchbox-ingress.yaml) manifest causes Matchbox (ssl-passthrough) to become unavailable. Rollback resolves the incident.

Investigate whether changes to the manifest are needed or if this is an Ingress controller issue.

**Comment by dghubble** [comment]
Matchbox status with the following Nginx Ingress controllers:

### 0.9-beta.3

Works fine.

### 0.9-beta.4

Not working. According to the changelog, `ssl-passthrough` was refactored by https://github.com/kubernetes/ingress/pull/614. Part of this was then changed by https://github.com/kubernetes/ingress/pull/540

```
2017/06/13 19:16:42 [error] 23#23: *6 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) while SSL handshaking to upstream, client: 146.148.41.163, server: matchbox.dghubble.io, request: "GET / HTTP/1.1", upstream: "https://10.2.79.5:8080/", host: "matchbox.dghubble.io"
```

### 0.9-beta.5

Not working. The changelog notes that `ssl-passthrough` is broken in 09-beta.5.

```
2017/06/13 19:08:36 [error] 78#78: *101 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) while SSL handshaking to upstream, client: 104.155.77.122, server: matchbox.dghubble.io, request: "GET / HTTP/1.1", upstream: "https://10.2.79.5:8080/", host: "matchbox.dghubble.io"
```
### 0.9-beta.6, 0.9-beta.7

Not working. Includes an `ssl-passthrough` fix https://github.com/kubernetes/ingress/issues/694. However, it looks like some new kube apiserver calls were introduced, because the Nginx Ingress controller now violates the earlier RBAC policy.

```
error initially creating leader election record: User "system:serviceaccount:ingress:default" cannot create configmaps in the namespace "ingress". (post configmaps)
```

**Comment by dghubble** [comment]
For Kubernetes clusters enabling RBAC (ideally everyone), adding configmap create to the Ingress ClusterRole was needed to address the error log in 0.9-beta.6 and 0.9-beta.7.

```
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
```

**Comment by dghubble** [comment]
With 0.9-beta.4 through 0.9-beta.7 (latest at time of writing), the crux of the issue seems to be having an Ingress resource for two different services (one HTTP and one HTTPS with ssl-passthrough). I believe its using ssl-passthrough for both services (instead of just the TLS one) and likely related to the Nginx Ingress controller ssl-passthrough rewrite in 0.9-beta.4.

My solution was to split the Ingress resources for the matchbox (read-only HTTP service) and matchbox-rpc (gRPC TLS service which does its own TLS termination). I'll update the contrib example shortly.

**Comment by dghubble** [comment]
Related https://github.com/kubernetes/ingress/issues/820, https://github.com/kubernetes/ingress/issues/206

**Comment by dghubble** [comment]
Proposed solution is splitting the old Ingress resource:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: matchbox
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - hosts:
        - matchbox-rpc.example.com
  rules:
    - host: matchbox.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: matchbox
              servicePort: 8080
    - host: matchbox-rpc.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: matchbox
              servicePort: 8081
```

into an Ingress resource for the HTTP service and an Ingress resource for the TLS gRPC service.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: matchbox
spec:
  rules:
    - host: matchbox.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: matchbox
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: matchbox
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - hosts:
        - matchbox-rpc.example.com
  rules:
    - host: matchbox-rpc.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: matchbox
              servicePort: 8081
```
