### ISSUE TITLE
disk partition size parameter -  unknown unit

### ISSUE THREAD

**Issue by maikotz** [coreos/matchbox#631]
In which unit is the size parameter in the ignition config ? 

I'm getting the error:

```
bootcfg[5]: time="2017-08-07T12:24:47Z" level=error msg="error parsing Ignition config: units: unknown unit G in 20G"
```

I I found in the 2-0 docu that it should be sectors from the beginning, but even with just numbers it doesn't work.

Is someone using disk partitions successfully? 

Thanks

**Comment by maikotz** [comment]
Just to clarify everything a bit more:

I'm seeing in the [ContainerOS documentation](https://coreos.com/ignition/docs/latest/examples.html#create-a-raid-enabled-data-volume
) that for raid devices this should work:

```
{
  "ignition": { "version": "2.1.0" },
  "storage": {
    "disks": [
      {
        "device": "/dev/sdb",
        "wipeTable": true,
        "partitions": [{
          "label": "raid.1.1",
          "number": 1,
          "size": 20480,
          "start": 0
        }]
      },
```

But if I enable this in my yaml ignition 
```
storage:
  disks:
    - device: /dev/sda
      wipe_table: true
      wipeTable: true
      partitions:
        - label: ROOT
          size: 20480
          start: 0
        - label: DATA
          size: 0
          start: 0
```

I'll get the same:
`rkt[2005]: [1224117.643503] bootcfg[5]: time="2017-08-07T14:25:02Z" level=error msg="error parsing Ignition config: units: unknown unit  in 20480"``
