### ISSUE TITLE
Support merging of Container Linux Config

### ISSUE THREAD

**Issue by bernard-wagner** [coreos/matchbox#724]
When developing Container Config templates it is often helpful to separate the templates into reusable blocks. It would be useful to allow appending/merge of the YAML elements after rendering the templates:

Example Template:
```
{{- if index . "example1" }}
systemd:
  units:
    - name: example1.service  
      contents: | 
        example1
{{- end }}        
{{- if index . "example2"  }}
systemd:
  units:
    - name: example2.service  
      contents: | 
        example2
{{- end }}        
```

## Desired Outcome

```
systemd:
  units:
    - name: example1.service  
      contents: | 
        example1
    - name: example2.service  
      contents: | 
        example2
```

## Current Outcome

```
systemd:
  units:
    - name: example2.service  
      contents: | 
        example2
```

## Notes 

```
yq merge -a sample-1.yaml sample-2.yaml
```
