### ISSUE TITLE
Documentation to use files local.

### ISSUE THREAD

**Issue by jbpin** [coreos/matchbox#725]
Hi, 

I try to use ignition template with this kind of config:

```
...
files:
    - path: /home/core/test.md
      filesystem: root
      mode: 0664
      contents:
        local: "/test.md"
...
```
Unfortunately the ignition file generated has no content:

```
...
"files": [
  {
    "filesystem": "root",
    "group": {},
    "path": "/home/core/test.md",
    "user": {},
    "contents": {
    "source": "data:,",
    "verification": {}
    },
    "mode": 436
  }
]
...
```
This is from the lastest os docs: 

`local (string): the path to a local file, relative to the --files-dir directory. When using local files, the --files-dir flag must be passed to ct. The file contents are included in the generated config.`

There is a way to give matchbox this `--files-dir` flag ? What the default value instead ? Where should I put the `test.md` file ?

Thanks
