### ISSUE TITLE
format for file content variable

### ISSUE THREAD

**Issue by dmitrijsf** [coreos/matchbox#743]
I am trying to find out the correct way to pass variable that represents file content (certificate in my case) but don't have any luck so far.

```sh
$ matchbox --version
v0.7.1
```

**Use case (not working):**

.tmpl file references variable

```yaml
---
storage:
  files:
    - filesystem: root
      path:       /etc/kubernetes/ssl/kubelet-{{.hostname}}.pem
      mode:       0644
      contents:
        inline: |
          {{.kubelet_cert_file}}
```

minion.tf - certificate file is either being generated by Terraform or is referenced with _file_ function.

```hcl
resource "matchbox_group" "minion1" {
  name    = "minion1"
  profile = "${matchbox_profile.minion.name}"

  selector {
	mac = "00-00-00-00-00-21"
	os = "installed"
  }

  metadata {
  hostname = "minion1"
  kubernetes_version = "${var.kubernetes_version}"
  kubelet_cert_file = "${tls_locally_signed_cert.minion1.cert_pem}"
}
```
results in failed config generation when calling url
```
http://matchbox.site.eu:8080/ignition?uuid=1f7e4d56-6212-6b30-f21d-d68106da6d53&mac=00-00-00-00-00-21&os=installed
```
error:
```
Mar 17 21:22:22 matchbox matchbox[985]: time="2019-03-17T21:22:22Z" level=error msg="error parsing Container Linux config: error: yaml: line 15: could not find expected ':'
```

**Workaround**
Providing the certificate information directly in template which breaks the profile modularity.

```yaml
---
storage:
  files:
    - filesystem: root
      path:       /etc/kubernetes/ssl/kubelet-{{.hostname}}.pem
      mode:       0644
      contents:
        inline: |
          -----BEGIN CERTIFICATE-----
          MIIDgjCCAmqgAwIBAgIUZyxAfn2ev0BnTsC1tvuHG/Hkp2QwDQYJKoZIhvcNAQEL
          <snip>
          IvcqMB0QTW9FP2rZGAHsBGJFmUw/8UMG3ohHD/MOlPWxG9utttA=
          -----END CERTIFICATE-----
```

**Comment by dmitrijsf** [comment]
Issue is solved by encoding the input to base64.

**minion.tf**

```
resource "matchbox_group" "minion1" {
  name    = "minion1"
  profile = "${matchbox_profile.minion.name}"

  selector {
	mac = "00-00-00-00-00-21"
	os = "installed"
  }

  metadata {
  hostname = "minion1"
  kubernetes_version = "${var.kubernetes_version}"
  kubelet_cert_file = "${base64encode(tls_locally_signed_cert.minion1.cert_pem)}"
```

**tmpl file**

```
---
  - filesystem: root
    path: "/etc/kubernetes/ssl/kubelet-{{.hostname}}.pem"
    mode: 420
    contents:
      inline: !!binary |
        {{.kubelet_cert_file}}
```
